application: emptext
version: 1
runtime: python
api_version: 1

handlers:
#favicon
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

#pacman
- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

#Hello world!
- url: /.*
  script: index.py

