application: emptext
version: 1
runtime: python
api_version: 1

handlers:
#favicon
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

#js
- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

#INDEX
- url: /.*
  static_files: static/regular/index.html
  upload: static/regular/index.html

